ecomm/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stores.urls')),

    #password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='password/reset_password.html'), name="reset_password"),

    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(template_name='password/reset_password_sent.html'), name="password_reset_done"),

    path('reset/<uidb64', auth_views.PasswordResetConfirmView.as_view(template_name='password/reset.html'), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetConfirmView.as_view(template_name='password/reset_password_complete.html'), name="password_reset_complete"),


]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.index, name='index'),
    path('category/',views.category,name='category'),
    path('singleproduct/<slug:slug>/',views.singleproduct,name='singleproduct'),
    path('addtocart/<int:id>/',views.addtocart,name='addtocart'),
    path('myCart/',views.myCart,name='myCart'),
    path('manageCart/<int:id>/',views.manageCart,name='manageCart'),
    path('emptyCart/',views.emptyCart,name='emptyCart'), 
    path('checkout/',views.checkout,name='checkout'),
    path('register/',views.register,name='register'),
    path('loginuser/',views.loginuser,name='login'),
    path('logoutuser/',views.logoutuser,name='logoutuser'),
    path('profile/',views.profile,name='profile'),
    path('order-detail/<int:id>/',views.orderDetails,name='order-detail'),
    path('search/',views.search,name='search'),
    path('transfer/',views.transferPage,name='transfer'),
    path('payment/<int:id>/',views.paymentPage,name='payment'),
    path('<str:ref>/',views.verify_payment,name='verify-payment'),




]

stores/models.py
from django.db import models
from django.contrib.auth.models import User

from .paystack import PayStack 
import secrets


# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null =True,blank=True)
    registered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title




class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    image = models.ImageField(upload_to="products") 
    price = models.PositiveIntegerField()  
    discount_price = models.PositiveBigIntegerField()
    description = models.TextField()   
    warranty = models.CharField(max_length=200, null=True,blank=True)
    return_policy = models.CharField(max_length=200, null=True,blank=True)
    view_count = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, null=True,blank=True)
    def __str__(self):
        return self.title

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,null=True,blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.customer} ::: {self.total}'   

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,null=True,blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __strt__(self):
        return f'{self.rate} ::: {self.quantity}'
	


OREDER_STATUS = (
	('Order Recieved','Order Recieved'),
	('Order Processing','Order Processing'),
	('On the way','On the way'),
	('Order Completed','Order Completed'),
	('Order Canceled','Order Canceled'),
	)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by =models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=11)
    email = models.EmailField(null=True,blank=True)
    discount = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=200, choices=OREDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
	
    payment_method = models.CharField(max_lenght=200, choices=METHOD,default='Cash on Delivery')
    payment_completed = models.NullBooleanField(default=False,null=True,blank=True)
    ref = models.CharField(max_lenght=20,null=True, blank=True)


    def __str__(self):
        return f'{self.order_status} ::: {self.total}'


    def save(self, *args, **kwargs):
        while not self.ref: 
            ref = secrets.token_urlsave(50)
            obj_with_sm_ref = Order.objects,filter(ref=ref)
            if not obj_with_sm_ref:
                self.ref= ref
        super().save(*args, **kwargs)     


    def amount_value(self) -> int:
        return self.total * 100
    def verify_payment(self):
        paystack = PayStack()
        status, result = payment.verify_payment(self.ref, self.total)  
        if status:
            if result['total']/100 == self.total:
                self.payment_complete=True
            self.save()
        if self.payment_completed:
         self.save()
        if self.payment_completed:
            return True
        return False    



OREDER_STATUS = (
    ('order Received','Order Received'),
    ('order Processing','Order Processing'),
    ('On the way','On the way')
    ('order completed','Order completed')
)        




METHOD = (
    ('Cash on Delivery','Cash on Delivery')
    ('Paystack','Paystack')
     ('Payment Transfer','Payment Transfer')
    
)

stores/forms.py
from django import forms
from . models import *

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['ordered_by','shipping_address','mobile','email']
        widgets ={
            'ordered_by':forms.TextInput(attrs={'class':'form-control'}),
            'shipping_address':forms.TextInput(attrs={'class':'form-control'}),
            'mobile':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),

        }


class CustomerRegister(forms.ModelForm):
    password1 = forms.CharField(label=('Password'),widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label=(' Confirm Password'),widget=forms.PasswordInput(attrs={'class':'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Customer 
        fields = ['full_name','email','username','password1', 'password2','address']
        widgets ={
            'full_name':forms.TextInput(attrs={'class':'form-control'}),
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
            'username':forms.TextInput(attrs={'class':'form-control'}),
        }

stores/views.py
from django.conf import settings
from django.http import JsonResponse
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from multiprocessing import AuthenticationError
from xml.etree.ElementTree import QName

from django.shortcuts import render, redirect

from django.contrib import messages
from django.core.paginator import Paginator

from django.db.models import Q 

from .forms import CheckoutForm, CustomerRegister
from .models import *

from django.contrib.auth import login,logout, authenticate 

from django.contrib.auth.decorators import login_required


from . models import *
# Create your views here.



def index(request):
    allproduct = Product.objects.all()
    context = {
        'show':allproduct
    }
    return render(request, 'stores/index.html',context)


def category(request):
    allcategory= Category.objects.all()
    context = {
        'category':allcategory
    }  

    return render(request, 'stores/category.html',context) 


def singleproduct(request,slug):
    singleproduct = Product.objects.get(slug=slug) 
    singleproduct.view_count+=1
    singleproduct.save()  
    context = {
        'show': singleproduct
    }
    return render(request, 'stores/single-product.html', context)


   # add product to cart 

def addtocart(request,id):
    # get the
    cart_product = Product.objects.get(id=id)
    # check if cart exist
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart_item = Cart.objects.get(id=cart_id)
        this_product_in_cart = cart_item.cartproduct_set.filter(product=cart_product)

        # assign cart to user 
        if request.user.is_authenticated and request.user.customer:
            cart_item.customer = request.user.customer
            cart_item.save()
        #end 
        #  checking if item exist in cart   

        if this_product_in_cart.exists():
            cartproduct = this_product_in_cart.last()
            cartproduct.quantity += 1
            cartproduct.subtotal += cart_product.price
            cartproduct.save()
            cart_item.total += cart_product.price
            cart_item.save()
            messages.success(request, 'item increase in cart')

            # new item in cart 

        else:
            cartproduct = CartProduct.objects.create(
                cart=cart_item, product=cart_product, rate=cart_product.price,
                quantity=1, subtotal=cart_product.price)
            cart_item.total += cart_product.price
            cart_item.save()
            messages.success(request, 'New item added to cart')

    else:
       cart_item = Cart.objects.create(total=0)
       request.session['cart_id'] = cart_item.id
       cartproduct = CartProduct.objects.create(cart=cart_item, product
       =cart_product, rate = cart_product.price, quantity=1, subtotal=cart_product.price)
       cart_item.total += cart_product.price
       cart_item.save()
       messages.success(request, 'New item to cart')
    return render(request, 'stores/index.html')   

# my cart 
def myCart(request):
    cart_id = request.session.get('cart_id', None)  
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
       # assign cart to user 
        if request.user.is_authenticated and request.user.customer:
            cart.customer = request.user.customer
            cart.save()
        #end 
    else:
        cart = None
    context = {
            'cart':cart,
        }
    return render(request, 'stores/mycart.html',context)




def manageCart(request,id):

    action = request.GET.get('action')
    cart_obj = CartProduct.objects.get(id=id)
    cart = cart_obj.cart
    
    if action == 'inc':
        cart_obj.quantity += 1
        cart_obj.subtotal += cart_obj.rate
        cart_obj.save()
        cart.total += cart_obj.rate
        cart.save()
        messages.success(request, 'item quantity increase in cart')

    elif action == 'dcr':
        cart_obj.quantity -= 1
        cart_obj.subtotal -= cart_obj.rate
        cart_obj.save()
        cart.total -= cart_obj.rate
        cart.save()
        messages.success(request, 'item quantity decrease in cart')

        if cart_obj.quantity == 0:
            cart_obj.delete()
    elif action == 'rmv':
        cart.total -= cart_obj.subtotal
        cart.save()
        cart_obj.delete()
        messages.success(request, 'item remove in cart')
    else:
        pass
    return redirect('myCart')   

def emptyCart(request):
    cart_id = request.session.get('cart_id', None)
    if cart_id:
        cart = Cart.objects.get(id=cart_id)
        # assign to cart
        if request.user.is_authenticate and request.user.customer:
            cart.customer = request.user.customer
            cart.save()
        #end 
        cart.cartproduct_set.all().delete()
        cart.total = 0 
        cart.save() 
        messages.success(request, 'All item in cart deleted') 
    return redirect('myCart') 




#Checkout
def checkout(request):
    cart_id = request.session.get('cart_id', None)
    cart_obj = Cart.objects.get(id=cart_id)
    form = CheckoutForm

    # checkout authentication
    if request.user.is_authenticated and request.user.customer:
        pass
    else:
        return redirect('/loginuser/?next=/checkout/')

    # getting cart

    if cart_id:
        cart_obj = Cart.objects.get(id=cart_id)
        # assign to cart
        # assign cart to user 
        if request.user.is_authenticated and request.user.customer:
            cart_obj.customer = request.user.customer
            cart_obj.save()
        #end 
    else:
        cart_obj =  None

    # Form

    if request.method == 'POST':
        form = CheckoutForm(request.POST or None)
        if form.is_valid():
            form = form.save(commit=False)
            form.cart = cart_obj
            form.discount = 0 
            form.subtotal = cart_obj.total
            form.total = cart_obj.total
            form.order_status = 'Order Received'
            pay_mth = form.payment_method
            del request.session['cart_id']
            pay_mth = form.payment_method
            form.save()
            order = form.id
            if pay_mth == 'Paystack':
                return redirect('payment', id =order)
            elif pay_mth == 'Payment Transfer':
                return redirect('transfer')    
            messages.success(request, 'Order have been placed successfully')
            return redirect('index')
        else:
            messages.error(request, 'No Order have been placed')
            return redirect('index')


    context = {
           'cart':cart_obj,
           'form':form,
       }  
    return render(request,'stores/checkout.html',context)   


# Customer Register 
def register(request):
    if request.user.is_authenticated:
        return redirect('index')
    form = CustomerRegister()
    if request.method == 'POST':
        form = CustomerRegister(request.POST or None)
        if form.is_valid():

            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')
            if User.objects.filter(username= username).exists():
                messages.success(request, 'User already exist')
                return redirect('register')
            if User.objects.filter(email= email).exists():
                messages.success(request, 'Email already exist')
                return redirect('register')
            if password != password2:
                messages.warning(request, 'password does not match')
                return redirect('register')
            user = User.objects.create_user(username,email,password)
            form = form.save(commit=False)
            form.user=user
            form.save()
            messages.success(request, 'Registration successful')
            if "next" in request.GET:
                next_url=request.GET.get("next")
                return redirect(next_url)
            else:
                return redirect('login')    


    context = {
       'form':form
   } 
    return render(request, 'stores/register.html',context)

       
def  loginuser(request):
    if request.user.is_authenticated:
        return redirect('index')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        users = authenticate(request, username = username, password = password)
        if users is not None:
            login(request, users)
            messages.success(request, 'User Login  successfully')
            if "next" in request.GET:
                next_url=request.GET.get("next")
                return redirect(next_url)
            else:
                return redirect('index')
        else:
            messages.error(request, 'Username/ password not correct')
    return render(request,'stores/login.html') 

def logoutuser(request):
    logout(request)
    messages.success(request, 'Logout successful') 
    return redirect('index')          


# Profile Message

def profile(request):
    if request.user.is_authenticated and request.user.customer:
        pass
    else:
        return redirect('/loginuser/?next=/profile')

    customer = request.user.customer
    orders = Order.objects.filter(cart__customer = customer).order_by('-id')
    context = {
       'customer':customer,
       'orders':orders
   } 
    return render(request, 'stores/profile.html',context)

    #order details of customers 
def orderDetails(request,id):
    if request.user.is_authenticated and request.user.customer:
        order = Order.objects.get(id=id) 
        if request.user.customer != order.cart.customer:
            return redirect('profile')
    else: 
        return redirect('/login/?next=/profile/')  
    orders = Order.objects.get(get=id)
    context = {

templates/stores/addtocart.html
{% extends "base.html" %}

{% load static %}
{% load humanize%}
{% block content %}


<h1>Product added successfully</h1>






{% endblock content %}

templates/stores/category.html
{% extends "base.html" %}

{% load static %}
{% load humanize%}
{% block content %}



<!-- featured  -->
<section id="featured" class="py-4 my-3">
    <div class="container">
        <!-- intro -->
       <div class="intro mb-5">
        <h2 class="text-center">
            <span>&#8668;</span> Category(s) <span>&#8669;</span>
        </h2>
       </div>
       {% if category  %}
       {% for cat in category %}
       <h1>{{cat.title}}</h1>
       <div class="row">
           {% for item in cat.product_set.all %}
           <div class="col-12 col-md-3">
            <a href="{% url 'singleproduct' item.slug %}">
                <div class="product">
                    <img src="{{ item.image.url }}" alt="" class="img-fluid">
                    <h5>{{item.title}}</h5>
                    <h6>
                        {% if item.discount_price %}
                        &#8358; {{item.discount_price | intcomma}} <del>&#8358; {{item.price}} </del>
                        {% else %}
                        &#8358; {{item.price | intcomma}}
                        {% endif %}
                    </h6>
                    <div class="stars">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i> 
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                    <a href="{% url 'addtocart' item.id %}" class="btn btn-dark">ADD TO CART</a> 
                   </div>
            </a>
            </div>
           {% endfor %}
        </div>
           {% endfor %}
         {% else %}
           <p class="lead bg-danger p-3 m-3 text-center">No Category</p>
         {% endif %}

    </div>
    </div>
</section>







  
{% endblock content %}

templates/stores/checkout.html
{% extends "base.html" %}

{% load static %}
{% load humanize%}
{% block content %}


<section id="checkout" class="py-5 my-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card p-3">
                    <h4 class="display-5 text-center">Items In Cart</h4>
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>SN</th>
                            <th>Product Name</th>
                            <th>Unit Price</th>
                            <th>Quantity</th>
                            <th>Subtotal</th>
                          </tr> 
                        </thead>
                        <tbody>
                          {% if cart %}
                            {% for item  in cart.cartproduct_set.all  %}
                              <tr>
                                  <td>
                                      {{forloop.counter}}
                                    </td>
                                    
                                    <td>{{item.product.tittle}}</td>
                                    <td>&#8358; {{item.rate | intcomma}}</td>
                                    <td>{{item.quantity}}</td>
                                    <td><strong> &#8358; {{item.subtotal | intcomma}}</strong></td>
                              </tr>
                            {% endfor %}
                            <tr> 
                                <th colspan="6">
                                    <h2>Total : &#8358; {{cart.total | intcomma}} </h2>
                                </th>
                            </tr>
                          {% else %}
                              <tr>
                                  <p class="lead bg-danger text-white p-3 m3"></p>
                              </tr>
                            
                          {% endif %}
                          <tr>
                              <td colspan="2">
                                <div class="d-grid">
                                  <a href="{% url 'myCart' %}" class="btn btn-outline-danger">
                                    Back to Cart 
                                  </a>
                                </div>
                              </td>
                            </tr>
                        </tbody>
                      </table>

                </div>

            </div>
            <div class="col-md-6">
                <div class="card p-3">
                    <h4 class="display-5 text-center">Checkout Form</h4>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <div class="d-grid">
                            <button type="submit" class="btn btn-info">Place Order</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>





{% endblock content %}

templates/stores/index.html
{% extends "base.html" %}

{% load static %}
{% load humanize%}
{% block content %}

<!-- swiper banner -->
<div class="swiper banner">
    <div class="swiper-wrapper">
      <div class="swiper-slide">
          <img src="{% static 'img/slider-1 (1).webp' %}" alt="">
      </div>
      <div class="swiper-slide">
        <img src="{% static 'img/slider-2.webp' %}" alt="">

      </div>
      <div class="swiper-slide">
        <img src="{% static 'img/slider-3.webp' %}" alt="">

      </div>                                                                                                                                                                                                                                    

    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>

<section id="featured" class="py-4 my-3">
    <div class="container">
        <!-- intro -->
       <div class="intro mb-5">
        <h2 class="text-center">
            <span>&#8668;</span> Category <span>&#8669;</span>
        </h2>
       </div>
</section>

<!-- featured  -->
<section id="featured" class="py-4 my-3">
    <div class="container">
        <!-- intro -->
       <div class="intro mb-5"> 
        <h2 class="text-center">
            <span>&#8668;</span> Featured <span>&#8669;</span>
        </h2>
       </div>
       <!-- product list -->
       <div class="row">
         {% if show %}  
           {% for item  in show  %}
           <div class="col-12 col-md-3 image">
            <a href="{% url 'singleproduct' item.slug %}">
                <div class="product">
                    <img src="{{ item.image.url}}" alt="" class="img-fluid">
                    <h5>{{item.title}}</h5>
                    <h6>
                        {% if item.discount_price %}
                        &#8358; {{item.discount_price | intcomma}} <del>&#8358; {{item.price}} </del>
                        {% else %}
                        &#8358; {{item.price | intcomma}}
                        {% endif %}
                    </h6>
                    <div class="stars"> 
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i> 
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-half"></i>
                    </div>
                    <a href="{% url 'addtocart' item.id %}" class="btn">ADD TO CART</a>
                   </div>
            </a>
        </div>
           {% endfor %}
        
            <nav>
                <ul class="pagination">
                    {% if paginators.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page{{ paginators.previous_page_number}}" >Previous</a>
                  </li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">Previous</a>
                  </li>
                  {% endif %}
    
                  {% for i in paginators.paginators.page_range %}
                  {% if i == paginators.number %}
                  <li class="page-item active"><a class="page-link">{{i}}</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                  {% endif %}
                  {% endfor %}
                  
                  {% if paginators.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{paginators.next_page_number}}">Next</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                  </li>
                </ul>
            </nav>
         {% endif %}
        </div>
        {% else %}
        <p class="text-center lead bg-danger p-3 m-3">
            No Products
        </p>
          
        {% endif %}
    </div>
    </div>
</section>







  
{% endblock content %}

templates/stores/login.html
{% extends "base.html" %}

{% load static %}
{% load humanize%}
{% block content %}

 <!-- logo content -->
 <div class="wrapper">
    <div class="logo"> <img src="{% static 'img/logo.png' %}" alt=""> </div>
    <div class="text-center mt-4 name"> TechMeta </div>
       <form class="p-3 mt-3" method="post" action="">
           {% csrf_token %}
           <div class="form-field d-flex align-items-center"> <span class="far fa-user"></span> <input type="text" name="username" id="userName" placeholder="Username"> </div>
           <div class="form-field d-flex align-items-center"> <span class="fas fa-key"></span> <input type="password" name="password" id="pwd" placeholder="Password"> </div> <button class="btn mt-3">Login</button>
       </form>
       <div class="text-center fs-6"> <a href="{% url 'reset_password' %}">Forget password?</a> or <a href="{% url 'register' %}">Sign up</a> </div>
   </div>














{% endblock content %}

templates/stores/orderdetail.html
{% extends "base.html" %}

{% load static %}
{% load humanize%}
{% block content %}





 <section id="profile" class="py-3">
     
       <!-- Profile -->
       <div class="row">
           <div class="col-md-8 mx-auto">
               <h3>Order Detail</h3>
               <hr>
            <ul class="list-group">
                <li class="list-group-item">Order Id: <strong>#ECOMORE_{{orders.id}}</strong> </li>  
                <li class="list-group-item"> Order Status:<strong>{{orders.order_status}}</strong></li>
                <li class="list-group-item">Order Date:<strong>{{orders.created_at}} age</strong></li>
                <li class="list-group-item"> Customer Name: <strong>{{orders.ordered_by}}</strong></li>
                <li class="list-group-item">Customer Email: <strong>{{orders.email}}</strong></li>
                <li class="list-group-item">Customer phone: <strong>{{orders.mobile}}</strong></li>
                <li class="list-group-item">Customer Address: <strong>{{orders.shipping_address}}</strong></li>
            </ul>

           </div>
               <h4 class="display-4 text-center">Order Item</h4>
               <table class="table table-center">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Image</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quality</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% if orders %}
                    {% for order in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <img src="{{ url order.product.image }}" alt="img-fluid" width="100"></td>
                        <td><a href="{% url 'singleproduct' order.product.slug %}"></a></td>
                        <td>{{order.order_status}}</td>
                        <td><a href="{ url 'order.details' order.id}" target="_blank">{{order.product.title}}</a></td>
                        <td>{{order.rate}}</td>
                        <td>{{order.quantity}}</td>
                        <td>{{order.subtotal}}</td>
                    </tr>
                  
                    {% endfor %}
                    <tr>
                        <td colspan="2" class="text-end"><h3>Total: {{orders.total}}</h3></td>
                    </tr>
                    {% else %}
                    <tr>
                        <p class="lead bg-danger">No Order Yet</p>
                    </tr>                           
                      {% endif %}
             
                    
                </tbody>
               </table>
                   
               

           </div>
       </div>

     </div>

 </section>
          






  
{% endblock content %}

templates/stores/transfer.html
{% extends "base.html" %}
{% load static %}
{% load humanize%}
{% block content %}


<!-- Intro  -->
    <!-- Featured  -->
    <section id="featured" class="py-4 my-3">
        <div class="container">
            <div class="row">
                <div class="col-md-5 mx-auto">
                    <div class="card">
                        <h4>Account To Pay to</h4>
                        <p>GTBank: 0108995892</p>
                        <p>FCMB: 707860918</p>
                    </div>
                </div>
            </div>
        </div>



















    </section>









{% endblock content %}